### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by crcn** [opendesigndev/open-design-sdk#2]
Hi! I'm hooking up Open Design and running into an error with `importFigmaDesign`:

```
(node:51346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at ApiDesign.<anonymous> (/Users/crcn/Developer/public/paperclip/node_modules/@opendesign/api/dist/api-design.js:62:47)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/crcn/Developer/public/paperclip/node_modules/@opendesign/api/dist/api-design.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Code for this is here: https://github.com/crcn/paperclip/blob/dev/packages/paperclip-open-design/src/pull.ts#L42

Any idea what's going on?

**Comment by crcn** [comment]
Dug around a bit more and the issue is coming from here: https://github.com/opendesigndev/open-design-sdk/blob/master/api/src/api-design.ts#L70. Looks like this is because of a failed HTTP request to `/designs/{design_id}/summary`. Here's the HTTP response I'm seeing: 

```javascript
{
  statusCode: 200,
  headers: {
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '64f11809b96b3f51-ORD',
    'cf-request-id': '0a0a8d5a1800003f5178211000000001',
    connection: 'close',
    'content-encoding': 'br',
    'content-type': 'application/json',
    date: 'Fri, 14 May 2021 03:38:29 GMT',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    nel: '{"report_to":"cf-nel","max_age":604800}',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=x4Y%2BCp5ALo2VeZ1jRMELlnvuvOv8TcKvzuAsG4%2BIE%2FaqAVoKDdzfjiGbg73dDxsracONTHfZGQju3Q59K5T4yUE698x9vkK6Wa8ihIfe6tE%2Bf21KL%2BJ5"}],"group":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding'
  },
  body: { id: '3dd87ccb-1d5a-4c6c-933d-dcbc16099f50', status: 'failed' }
}
```

**Comment by crcn** [comment]
Doh! Looks like I'm accidentally sending the Figma project ID to `importFigmaDesign` and not the file key. My bad!

**Comment by jankuca** [comment]
Hello,

thank you for the report. I'm happy you were able to figure out the cause. We will improve error handling for this case, there should be friendlier output in such situations. 

Jan

**Comment by jankuca** [comment]
There should be a proper error as of the SDK version 0.2.0.
