### ISSUE TITLE
Fallback fonts not working

### ISSUE THREAD

**Issue by xorb** [opendesigndev/open-design-sdk#25]
Hi guys, seems like fallback fonts are not being recognized. Systems fonts are working fine.

"@opendesign/sdk": "^0.4.5"
node: v14.19.3

### Error message:

```
(node:105008) UnhandledPromiseRejectionWarning: Error: Unknown font format
    at Object.fontkit.create (/home/xorb/Projects/ProgPack/parse-ai/node_modules/@avocode/fontkit/src/base.js:99:9)
    at SystemFontManager.<anonymous> (/home/xorb/Projects/ProgPack/parse-ai/node_modules/@opendesign/sdk/src/local/system-font-manager.ts:287:52)
    at Generator.next (<anonymous>)
```

### Project structure:

```
.
├── fonts
│   └── Inter-Regular.otf
├── package.json
├── Preview_text_multi.ai
├── src
│   ├── fonts
│   │   └── Inter-Regular.otf
│   └── index.ts
├── tsconfig.json
└── yarn.lock
```

## Config:

```ts
 const sdk = createSdk({ token: OPEN_DESIGN_TOKEN });
 sdk.setGlobalFontDirectory("./fonts");
 sdk.setGlobalFallbackFonts(["Inter-Regular"]);
```

Sample repo: https://github.com/xorb/opendesign-text-issue

**Comment by xorb** [comment]
I have been testing it on another linux distributions. No issues with Manjaro. Probably some package missing on the other linux distribution.

**Comment by xorb** [comment]
Seems like issue is back. Facing that issue again. It worked once.

**Comment by xorb** [comment]
In production, we are using Amazon ami linux 2. It works fine inside [vagrant](https://app.vagrantup.com/bento/boxes/amazonlinux-2). Probably we need to do some adjustments in our side.
