### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by w4ugit** [opendesigndev/open-design-sdk#40]
I want to install on Mac OS Ventura.

`error /Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@19.5.0 | darwin | arm64
node-pre-gyp info check checked for "/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@19.5.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@19.5.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@19.5.0 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/Cellar/node/19.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/Cellar/node/19.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/taruk/Library/Caches/node-gyp/19.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/taruk/Library/Caches/node-gyp/19.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/Cellar/node/19.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/taruk/Library/Caches/node-gyp/19.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@19.5.0 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    Backend* backend;
             ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:21:
../src/Util.h:25:7: error: no member named 'AccessorSignature' in namespace 'v8'
                v8::AccessorSignature::New(v8::Isolate::GetCurrent(), ctor)
                ~~~~^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/Cellar/node/19.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.4.0
gyp ERR! command "/opt/homebrew/Cellar/node/19.5.0/bin/node" "/opt/homebrew/Cellar/node/19.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
gyp ERR! cwd /Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas
gyp ERR! node -v v19.5.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/taruk/Node/design4u/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 22.4.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/19.5.0/bin/node" "/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas
node-pre-gyp ERR! node -v v19.5.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/taruk/Node/design4u/node_modules/@opendesign/svg-exporter/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/`

Node - v19.5.0
npm - 9.4.0
Yarn - 1.22.19

**Comment by w4ugit** [comment]
Changing dependencies in package.json helped me

`{
  "resolutions": {
    "canvas": "^2.11.0",
    "nan": "^2.17.0"
  },
  "overrides": {
    "canvas": "^2.11.0",
    "nan": "^2.17.0"
  },
  "dependencies": {
    "@opendesign/sdk": "^0.4.5",
    "canvas": "^2.11.0"
  }
}`

**Comment by w4ugit** [comment]
Done
